#!/bin/bash

git submodule update --init --recursive
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

ln -sf "$PWD/zshrc" "$HOME"/.zshrc
ln -sf "$PWD/starship.toml" "$HOME"/.starship.toml

ln -sf "$PWD/alacritty" "$XDG_CONFIG_HOME"/alacritty
ln -sf "$PWD/tmux" "$XDG_CONFIG_HOME"/tmux

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
nix-env -iA nixpkgs.myPackages
