#!/bin/bash

export XDG_CONFIG_HOME="$HOME/.config"
git submodule update --init --recursive

source packages
sudo pacman -Sy ${packages[@]}
if !command -v cargo &> /dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

ln -sf "$PWD/.zshrc" "$HOME"/.zshrc
stow . -t $XDG_CONFIG_HOME
