#!/bin/bash

export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

ln -sf "$PWD/alacritty" "$XDG_CONFIG_HOME"/alacritty
ln -sf "$PWD/zshrc" "$HOME"/.zshrc
ln -sf "$PWD/starship.toml" "$HOME"/.starship.toml

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
ln -sf "$PWD/tmux.conf" "$HOME"/.tmux.conf

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix

nix-env -iA nixpkgs.myPackages
