exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- hyprpaper
exec-once = uwsm-app -- dunst
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- spotify_player -d
exec-once = [workspace 1 silent] uwsm-app kitty tmux
exec-once = [workspace 2 silent] uwsm-app firefox

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
