# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

env = GDK_SCALE,2
monitor=,1920x1080,auto,auto

monitor=DP-2,2560x1440@60,-1440x-940,1,transform,3
monitor=DP-3,3440x1440@180,0x0,1

workspace=1,monitor:DP-3
workspace=2,monitor:DP-3
workspace=3,monitor:DP-3
workspace=4,monitor:DP-2
workspace=5,monitor:DP-2
workspace=6,monitor:DP-2
