session_name: default
start_directory: ~/development
windows:
  - window_name: nvim
    layout: main-horizontal
    options:
      main-pane-height: 75%
    panes:
    - shell_command:
      - nvim
      focus: True
    - shell_command:
      -
  - window_name: note
    panes:
    - shell_command:
      - nvim ~/samba/obsidian/master/index.md
