[items]
order = ["shutdown", "reboot", "logout", "lock", "suspend", "hibernate"]

[items.lock]
icon = ""
cmd = "hyprlock"

[items.shutdown]
icon = ""
cmd = "shutdown -h now"

[items.reboot]
icon = ""
cmd = "hyprshutdown --post-cmd 'reboot'"

[items.logout]
icon = ""
cmd = "hyprshutdown"

[theme.container]
border = false
border_color = "#9399b2"
border_rounded = true

[theme.title]
border = false
border_color = "#9399b2"
border_rounded = true
text_color = "#f2cdcd"

[theme.menu]
border = true
border_color = "#9399b2"
border_rounded = true
text_color = "#a6adc8"
selected_item_text_color = "#a6e3a1"

[theme.confirm_dialog]
border = true
border_color = "#9399b2"
border_rounded = true
text_color = "#a6adc8"
selected_option_text_color = "#a6e3a1"

[theme.footer]
border = false
border_color = "#9399b2"
border_rounded = true
text_color = "#6c7086"
